#!/bin/sh
#
# Postinst script for cntlm
#

set -e

NAME=cntlm
HOME=/var/run/cntlm

# Create cntlm user and its homedir
if ! getent passwd $NAME >/dev/null; then
	adduser --system --home $HOME --shell /bin/sh --disabled-password $NAME
fi

if ! [ -d $HOME ]; then
	mkdir -p $HOME
	chmod 755 $HOME
	chown -h -R $NAME $HOME
fi

#DEBHELPER#
