#!/bin/bash
# cNTLM per user launcher script
USER_CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}"
CNTLM_CONFIG_LOC="${USER_CONFIG_DIR}/cntlm/cntlm.conf"

if [ ! -e "${CNTLM_CONFIG_LOC}" ] ; then
  echo "${CNTLM_CONFIG_LOC} does not exist! Unable to run cNTLM for user ${USER}."
  exit 1
fi

exec /usr/sbin/cntlm -f -c "${CNTLM_CONFIG_LOC}"