name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: clean
      run: make clean

    # SonarCloud build and scan
    #- ./configure
    #- make clean
    - name: SonarCloud build wrapper 
      run: build-wrapper-linux-x86-64 --out-dir bw-output make
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
