name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install necessary packages
      run: sudo apt install -y libpacparser-dev libpacparser1
    - name: normal_build
      run: |
        ./configure
        make
        make distclean
    - name: unicode_build
      run: |
        ./configure
        CFLAGS=-DUNICODE make
        make distclean
    - name: pacparser_build
      run: |
        ./configure
        CFLAGS=-DENABLE_PACPARSER make
        make distclean
