name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install necessary packages
      run: sudo apt install -y libpacparser-dev libkrb5-dev 
    - name: Normal build
      run: |
        ./configure
        make
        make distclean
    - name: Unicode build
      run: |
        ./configure
        CFLAGS=-DUNICODE make
        make distclean
    - name: Build with pacparser enabled
      run: |
        ./configure --enable-pacparser
        make
        make distclean
    - name: Build with kerberos enabled
      run: |
        ./configure --enable-kerberos
        make
        make distclean
